name: 'arithmetic__mul_div_multiple'
task: 'arithmetic__mul_div_multiple_hard_5'
in_path: 'data/mathematics_dataset-v1.0/train-hard/'
out_path: 'experiments/'
example: [0,1]
start: 0
end: null
pool_size: 5
